### ISSUE TITLE
Apsplanner failed to import [Resolved]

### ISSUE THREAD

**Issue by blainecostello** [Voyz/databay#7]
Error on line: "from databay.planners import APSPlanner" 

I forget the exact error message and I'm unable to recreate the error now for some reason 

Looked like maybe some kind of issue linking the library on installation.  When I uncommented line 9 of the __init__ file the issue was resolved and everything worked as expected.  Now when I comment that line out everything still works as expected and the error is gone.

**Comment by Voyz** [comment]
Thank you for reporting! I've attempted to reproduce this on the latest release but everything seems to work fine. Could it be a typo possibly? There has been a similar issue (#2) before - `ASPlanner` instead of `APSPlanner` - so that would be my guess. I think I will rename this planner to `ApsPlanner` to make the distinction easier.

If that's okay with you I'm going to close this issue until the problem you're describing can be reproduced or is experienced by other users. Nonetheless thanks for bringing it up! 😊 Take care!
